CREATE DATABASE IF NOT EXISTS sgojava;
USE sgojava;

CREATE TABLE IF NOT EXISTS GRUPO_USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACAO VARCHAR(200),
    TABELA VARCHAR(200),
    VISUALIZAR BOOL DEFAULT FALSE,
    EDITAR BOOL DEFAULT FALSE,
    DELETAR BOOL DEFAULT FALSE,
    INCLUIR BOOL DEFAULT FALSE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FUNCAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    FUNCAO INT NOT NULL,
    FOREIGN KEY (FUNCAO) REFERENCES FUNCAO(ID) ON DELETE CASCADE,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USUARIO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    GRUPO_USUARIO INT NOT NULL,
    FOREIGN KEY (GRUPO_USUARIO) REFERENCES GRUPO_USUARIO(ID) ON DELETE CASCADE,
    FUNCIONARIO INT,
    FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(ID) ON DELETE CASCADE,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ESPECIE_ANIMAL(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS RACA_ANIMAL(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    ESPECIE INT NOT NULL,
    PORTE CHAR(1),
    FOREIGN KEY (ESPECIE) REFERENCES ESPECIE_ANIMAL(ID) ON DELETE CASCADE,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SAUDE_ANIMAL(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PESO DOUBLE,
    CASTRADO BOOL,
    OBSERVACAO_CASTRACAO VARCHAR(300),
    VACINADO BOOL,
    OBSERVACAO_VACINA VARCHAR(300),
    DOENTE BOOL,
    OBSERVACAO_DOENCA VARCHAR(300),
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ANIMAL(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE DOUBLE,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW(),
    RACA INT,
    FOREIGN KEY (RACA) REFERENCES RACA_ANIMAL(ID) ON DELETE CASCADE,
    SEXO CHAR(1),
	SAUDE INT,
    FOREIGN KEY (SAUDE) REFERENCES SAUDE_ANIMAL(ID) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ADOTANTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(200) NOT NULL,
    OBSERVACAO VARCHAR(500),
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW()
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ADOCAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_ADOCAO DATE NOT NULL,
    ANIMAL INT NOT NULL,
    ADOTANTE INT NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (ANIMAL) REFERENCES ANIMAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (ADOTANTE) REFERENCES ADOTANTE(ID) ON DELETE CASCADE
) ENGINE=INNODB;

INSERT INTO GRUPO_USUARIO(ACAO, TABELA, VISUALIZAR, EDITAR, INCLUIR, DELETAR) VALUES ("LICENÇA TOTAL", "TODAS", TRUE, TRUE, TRUE, TRUE);
INSERT INTO USUARIO(LOGIN, SENHA, GRUPO_USUARIO) VALUES ("sgo_master", "sgo", (SELECT MAX(ID) FROM GRUPO_USUARIO WHERE ACAO = "LICENÇA TOTAL"))