package utils;

public class Permissoes {
	public static String TOTAL_TELAS_SOBRE_ANIMAL = "TOTAL TELAS SOBRE ANIMAL";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_ANIMAL = "APENAS VISUALIZAR TELAS SOBRE ANIMAL";
	public static String APENA_VISUALIZAR_TELAS_SOBRE_DOACAO = "APENAS VISUALIZAR TELAS SOBRE DOACAO";
	public static String TOTAL_TELAS_SOBRE_DOACAO = "TOTAL TELAS SOBRE DOACAO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_FUNCAO = "APENAS VISUALIZAR TELAS SOBRE FUNCAO";
	public static String TOTAL_TELAS_SOBRE_FUNCAO = "TOTAL TELAS SOBRE FUNCAO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_FUNCIONARIO = "APENAS VISUALIZAR TELAS SOBRE FUNCIONARIO";
	public static String TOTAL_TELAS_SOBRE_FUNCIONARIO = "TOTAL TELAS SOBRE FUNCIONARIO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_GRUPO_PERMISSAO = "APENAS VISUALIZAR TELAS SOBRE GRUPO PERMISSAO";
	public static String TOTAL_TELAS_SOBRE_GRUPO_PERMISSAO = "TOTAL TELAS SOBRE GRUPO PERMISSAO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_GRUPO_USUARIO = "APENAS VISUALIZAR TELAS SOBRE GRUPO USUARIO";
	public static String TOTAL_TELAS_SOBRE_GRUPO_USUARIO = "TOTAL TELAS SOBRE GRUPO USUARIO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_PERMISSAO_USUARIO = "APENAS VISUALIZAR TELAS SOBRE PERMISSAO USUARIO";
	public static String TOTAL_TELAS_SOBRE_PERMISSAO_USUARIO = "TOTAL TELAS SOBRE PERMISSAO USUARIO";
	public static String APENAS_VISUALIZAR_TELAS_SOBRE_USUARIO = "APENAS VISUALIZAR TELAS SOBRE USUARIO";
	public static String TOTAL_TELAS_SOBRE_USUARIO = "TOTAL TELAS SOBRE USUARIO";
}
